name: Update

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

permissions: write-all

jobs:
  update:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3

    - name: Cleaning up the repository
      run: |
        [ -d "./content" ] && rm -rf ./content

    - name: Clone the current state repo
      uses: actions/checkout@v3
      with:
        repository: rust-lang-uz/i10n
        path: i10n

    - name: Update the content
      run: |
        # Move ordinary files first
        mv ./i10n/rustbook-uz ./content
        ls -la
        # Delete the cloned data
        sudo rm -rf ./i10
        ls -la
        
    - name: Setup git credentials
      run: |
        # Use github actions default username and email
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Push the content
      run: |
        git add .
        [[ -z $(git status -uno --porcelain) ]] && echo "this branch is clean, no need to push..." && exit 0;
        git commit -m "Updating $GITHUB_SHA content"
        git push --force